name: Kotlin CI

on:
  push:
    branches:
      - 'master' 
jobs:
  test:
    name: Run Units Test
    runs-on: windows-latest
    steps:
          - uses: actions/checkout@v1
          - name: set up JDK 1.8
            uses: actions/setup-java@v1
            with:
              java-version: 1.8
          - name: Units Tests
            run: bash ./gradlew wrapper; bash ./gradlew build
